theme = "rasmus"

[editor]
text-width = 90
line-number = "relative"
mouse = true
scrolloff = 10
bufferline = "multiple"
popup-border = "all"
continue-comments = false
# auto-completion = false # If I want to trigger by hands only
completion-timeout = 150
preview-completion-insert = false
completion-trigger-len = 2

[editor.soft-wrap]
enable = true
wrap-indicator = "â†ª"
# wrap-at-text-width = true

[editor.auto-pairs]
"'" = "'"
'"' = '"'
'`' = '`'

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"}" = ":buffer-next"
"{" = ":buffer-previous"
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]
C-U = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-D = ["extend_to_line_bounds", "delete_selection", "paste_after"]
";" = "repeat_last_motion"
# Just for my nav layer:
# C-left = "move_prev_word_start"
# C-right = "move_next_word_start"
C-up = ["page_cursor_half_up", "align_view_center"]
C-down = ["page_cursor_half_down", "align_view_center"]
C-S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.normal.g]
left = "goto_line_start"
right = "goto_line_end"

[keys.insert]
C-i = "completion"
