theme = "Mellow"

[editor]
line-number = "relative"
mouse = true
scrolloff = 10
bufferline = "multiple"
completion-timeout = 150
# auto-completion = false # If I want to trigger by hands only

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]
C-U = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-D = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

[keys.insert]
C-i = "completion"
